stm32-rs/stm32h7xx-hal

Cargo.toml
examples/i2c.rs
examples/watchdog.rs
src/gpio.rs
src/i2c.rs
src/lib.rs
src/prelude.rs
src/rcc.rs
src/serial.rs
src/spi.rs
src/time.rs
src/watchdog.rs

This PR merges in the stm32h7x3-hal project, bringing:
* An I2C implementation
* A Watchdog implementation
* Examples for both of them
Furthermore it adds myself as an author and replaces all the `...` inclusive range syntax with `..=` syntax instead as the first one has been deprecated.
Me and a friend of mine are currently also working on an ADC implementation, still for our version of the HAL so maybe it would be better to wait until we are done with it, ported it over and continue our work over at this version of the HAL.

Merging in stm32h7x3-hal

---

.travis.yml
Cargo.toml
README.md
src/adc.rs
src/gpio.rs
src/i2c.rs
src/lib.rs
src/qei.rs
src/rcc.rs
src/serial.rs
src/spi.rs
src/timer.rs

Upstream change in stm32-rs
https://github.com/stm32-rs/stm32-rs/pull/247
Remove feature gates where they are not required.
Add new v feature targets to travis.
ADC is currently the only area where this crate differs between v and
non-v.
Revision v tracking issue
https://github.com/stm32-rs/stm32h7xx-hal/issues/9

revision_v: Update feature gates from revision v split in PAC

---

src/pwm.rs
src/qei.rs
src/rcc.rs
src/serial.rs
src/timer.rs

 rcc: write accessors for AHB and APB busses in a macro

---

src/pwm.rs
src/qei.rs

svd2rust v0.15.0 makes the following breaking change ([changelog](https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#v0150---2019-07-25))
> [breaking-change] for access to alternate registers functions now
used instead of untagged_unions (no more nightly features)
Fix by making function calls for `cmrrX_output`.
Fixing this will be a breaking change for anyone building `stm32-rs`
locally. To bring your build enviroment up-to-date:
```
cargo install svd2rust --force
```
Closes #29
Unblocks #28 and others

svd2rust: breaking changes from update to v0.15.0

---

src/adc.rs
src/prelude.rs
src/time.rs
src/timer.rs

adc: Add initialisation trait
Simplifies usage:
```rust
let _ = adc::Adc::adc3(dp.ADC3, &mut delay, &mut ccdr);
```
to
```rust
let _ = dp.ADC3.adc(&mut delay, &mut ccdr);
```
Previous method still works.
Re-work arguments for timer, doesn't break anything as there aren't any examples yet.
Closes #20

Init traits prelude

---

examples/i2c.rs
src/i2c.rs
src/prelude.rs

Porting i2c to the extension trait pattern

---

examples/blinky_timer.rs
src/timer.rs

Previously the `CountDown` timer failed to start a new countdown if the periodic timer was running and no `wait()` call was made in the previous period. This was as the UIF bit was already set.
See embedded-hal docs for the contract:
https://docs.rs/embedded-hal/0.2.3/embedded_hal/timer/trait.CountDown.html#tymethod.start
Add  example to demonstrate correct behaviour.

timers, bugfix: fix periodic CountDown timer

---

examples/spi.rs
src/rcc.rs

* All 3 outputs of PLL1 can be configured.
* Moving closer to a generic interface for PLL2/PLL3; just needs macro
definitions and call to setup.
* An `assert` will occour if pll1_p_ck is set independently when it is
requried for sys_ck.
* When `pll1_r_ck` is `None` in the configuration struct, it is set if
required to keep `traceclk` running. Afaict there's no documentation
on acceptable frequencies for `traceclk`, set p_ck/2 as a sensible
choice (can be overridden by setting some `pll1_r_ck`).

rcc: add options to configure more PLL outputs

---

src/gpio.rs

According to RM0433, sec. 19.6.24, a "bit is cleared by writing a 1 into the bit or by changing the sensitivity of the edge detector."
I have not tested nor compiled this on stm32h7xx. However, I found this issue while porting the ExtiPin trait to stm32f1xx. I have tested this change on my stm32f1xx-hal working copy.
See also stm32-rs/stm32f4xx-hal#114

Fix clear_interrupt_pending_bit()

---

Cargo.toml

Correct to the terminology used in the embedded rust book
https://docs.rust-embedded.org/book/portability/

Update crate description

---

src/rcc.rs

Add alternative PLL configuration strategy, which can be selected instead of the current default.
This strategy uses the high frequency VCO, and iterates the M divider value to give an accurate frequency on the P output.
**Normal**: VCOL, highest PFD frequency, highest VCO frequency
**Iterative**: VCOH, choose PFD frequency for accuracy, highest VCO frequency

Iterative PLL strategy

---

src/i2c.rs

It appears to take some additional cycles of PCLK to end the previous
address sequence, after we may have returned with an ACK or NACK. Wait
for this. Once the START bit is clear, we can set it even whilst the
bus is busy, as explicitly stated in a note by the START bit in the RM.

i2c: wait for end of previous address phase before setting START

---

.travis.yml
README.md

Update README to be clearer and more useful to those new to embedded rust. Prefer linking to more general embedded rust resources instead of giving build instructions ourselves. [Rendered here](https://github.com/richardeoin/stm32h7xx-hal/blob/readme1/README.md)
Add minimum supported rust version (MSRV).
Stop running run CI against beta rust.

Improve README.md, add minimum supported rust version

---

Cargo.toml

The `target` field does nothing. There are two options you could have been trying to set:
- `default-target`, the target built for the main page (docs.rs/stm32h7xx-hal)
- `targets`, which controls all targets built.
This changes it to the second since I assume `stm32h7xx-hal` is the only target you want to build, but I can change it to the first if you want to build all tier one platforms instead.

Fix invalid docs.rs `targets` syntax

---

src/i2c.rs

Also remove unsafe keyword on traits that don't need it.
After this the i2c hal is completely free of `unsafe`.

bugfix i2c: Fix reference to I2C1 in macro generic for all I2Cs

---

.travis.yml
Cargo.toml
README.md
examples/safe_enable_fdcan.rs
src/lib.rs
src/rcc/mod.rs
src/rcc/rec.rs

Safe access to enable, disable and reset peripherals that are not used in this hal.
Uses a macro with https://github.com/dtolnay/paste for brevity.
From discussion on #66

A safe interface for the user and other crates to access the RCC

---

examples/README.md
src/pwr.rs

And a bugfix: In the case of the default mode, we should not modify CR3 at
all. Therefore the default mode should now work for dualcore parts with no
SMPS (if these even exist, I haven't checked).

SMPS: Add documentation describing Run* mode, and in examples folder

---

src/adc.rs

The PR adds a `.free()` method to the ADCs in a style similar to many of the other peripherals.

implement free() for ADC

---

examples/adc.rs
examples/blinky.rs
examples/blinky_random.rs
examples/blinky_timer.rs
examples/i2c.rs
examples/pwm.rs
examples/rtfm.rs
examples/rtfm_timers.rs
examples/sai_pdm.rs
examples/serial.rs
examples/spi.rs
examples/temperature.rs
src/adc.rs
src/gpio.rs
src/i2c.rs
src/pwm.rs
src/qei.rs
src/rcc/mod.rs
src/rcc/rec.rs
src/rng.rs
src/sai/mod.rs
src/sai/pdm.rs
src/serial.rs
src/spi.rs
src/timer.rs

For peripeherals used in this crate.
After this, periperhal initialisations will generally have a function
signature ending `..., ccdr.peripheral.XXX, &ccdr.clocks);`

Use marker types for Reset / Enable of peripherals within the crate also

---

README.md

This looks like a nice H7 board (if a bit expensive?), but a quick scan of the [schematic](https://content.arduino.cc/assets/Arduino-PortentaH7-schematic-V1.0.pdf) shows that the usual programming interfaces are only on difficult-to-solder high density connectors. The stm32 bootloader is only on the *other* USB port (USB_FS).
I think a little expectations management is therefore appropriate, especially to warn new users. If someone has a board to test, we can then update with more details.

Note about programming Arduino H7 board

---

src/timer.rs

This PR fixes #72 by triggering a timer update event to ensure the ARR register is updated.

Fixes #72: Timer first cycle invalid

---

.github/bors.toml
.github/workflows/ci.yml
Cargo.toml
README.md
examples/vos0.rs
src/pwr.rs

Looking at how VOS0 scaling needs to be implemented the current structure is going to need to be broken a bit I opted to create a new freeze_vos0 function to not break all the existing code.
> Setup PWR...
> Setup RCC...
> 
> stm32h7xx-hal example - RCC
> 
> hclk = 240 MHz
> sys_ck = 480 MHz
RM0433 rev 7
> VOS0 activation/deactivation sequence
> The system maximum frequency can be reached by boosting the voltage scaling level to
> VOS0. This is done through the ODEN bit in the SYSCFG_PWRCR register.
> The sequence to activate the VOS0 is the following:
> 
> 1. Ensure that the system voltage scaling is set to VOS1 by checking the VOS bits in
> PWR D3 domain control register (PWR D3 domain control register (PWR_D3CR))
> 
> 2. Enable the SYSCFG clock in the RCC by setting the SYSCFGEN bit in …

Updated pwr to handle vos0

---

.github/workflows/ci.yml
.github/workflows/clippy.yml
.github/workflows/nightly.yml
examples/adc.rs
examples/blinky.rs
examples/blinky_random.rs
examples/blinky_timer.rs
examples/dac.rs
examples/mco.rs
examples/pwm.rs
examples/rcc.rs
examples/sai_pdm.rs
examples/serial.rs
examples/spi.rs
examples/temperature.rs
examples/vos0.rs

Also provide clippy lints. Only `deny`/`forbid` lints will fail the build, unless `#[deny(warnings)]` is also specified.

CI: Continue if nightly fails

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Cargo.toml
README.md
examples/sdmmc.rs
src/lib.rs
src/prelude.rs
src/sdmmc.rs

Uses [sdio-host](https://crates.io/crates/sdio-host).
Requires `sdmmc` feature gate.

Add SDMMC and example

---

src/pwm.rs

Before, it was possible to pass any tuple of TIMx pins to TIMx.pwm(...)
and it would succeed: you could pass two different pins for CH1 or pins
for CH3 and CH4 and either way you would get PWM channels 1 and 2
which would end up writing to the wrong peripheral registers and trying
to use PWM channels with no pins configured.
To fix this, pwm::Pins<TIM> was changed to pwm::Pins<TIM, CHANNEL> and
a pin is now associated with a specific PWM channel.
Tuples of pins and channels are now marked with which channels they
are associated, such as (C1, C2, C3) or (C4, C2)
Pins is only implemented for tuples of channels with no repeated
channels, and each Pins implementation uses the correct Channels tuple
based on the channels for the tuples of pins it is implemented for.
The implementation of …

Added pwm channel info to pwm::Pins

---

Cargo.toml
examples/fractional-pll.rs
src/rcc/pll.rs

I've implemented a fractional strategy. The math could definitely use double checking. There are some corner cases that may need additional work such as the pll3_r_ck below being below the target value instead of above, but that would require adjusting the other clocks i think, so it may just be a oddity.
Is there a good way to confirm the output clock values short of throwing a scope on it ( I don't have one)?
```
PllConfigStrategy::FractionalNotLess
sys_ck = 400 MHz
pll3_p_ck = 12288002 MHz (target was 12_288_000)
pll3_q_ck = 6144001 MHz (target was 6_144_000)
pll3_r_ck = 3023546 MHz (target was 3024000)
```
Closes #98

Implemented initial fractional strategy

---

src/i2c.rs

Currently the `write()` method returns once the final byte is written to the FIFO, not when the transaction finishes. Although this saves one byte of time, it is somewhat awkward because:
* Calling another i2c method during this time will fail.
* I2C events are not raised until the transfer ends.
At some point we will need to re-write all of this for async and DMA, but for now I think this is less confusing.

i2c: Extend i2c::Write implementation method and add events

---

src/delay.rs

Fix Delay clock divider on Rev V chips

---

examples/serial.rs
src/lib.rs
src/serial.rs
src/time.rs

* Allow baud rate in Hertz/KiloHertz as well as Bps
* Accept a baud rate instead of a configuration struct. In the case that a baud rate is specified, the defaults for the other parameters (8N1) are used.
* Rename `usart` / `usart_unchecked` extension methods to `serial` / `serial_unchecked`. The method names elsewhere match the module name, and also some peripherals are `uart` not `usart`, so I think `serial` is an improvement. Keep the old methods for backwards compatibility.
No breakage, but I have updated the example.

Improvements to serial

---

examples/spi.rs
src/spi.rs

With the addition of these functions, it becomes quite easy to share an SPI peripheral between multiple devices which require different configuration. You can `disable()`, `free()`, then pass ownership between the different devices which can then configure the SPI peripheral.

Add SPI enable disable

---

src/i2c.rs

Tests from RM0433 and I2C specification (UM10204)
Adjust SDADEL/SCLDEL values slightly so they pass the tests in all cases. Changes:
Sm SCLDEL `i2cclk / 800_000 / presc - 1` -> `i2cclk / 500_000 / presc - 1`
Fm SDADEL `i2cclk / 8_000_000 / presc` -> `i2cclk / 4_000_000 / presc`
Fm+ SDADEL `2` -> `i2cclk / 8_000_000 / presc`

Add tests for I2C timing, adjust SDADEL/SCLDEL

---

src/time.rs
src/timer.rs

I have a use-case where I need to set a specific timer timeout (using interrupts).
Of course it would be possible to convert the delay into a frequency, but then it would involve one division (delay -> Hz) and another one back (Hz -> delay).  It seemed more natural to support duration delays directly.
It might also make sense to use `CountDown<Time=Duration>` as well, but since there is already a `CountDown<Time=Hz>` I couldn't add a conflicting one.  However it might make sense to reconsider whether it makes sense to measure a duration in Hz, as is currently the case in this crate?

Add a set_timeout method for timers

---

src/rcc/mod.rs

* Add flash wait state table for VOS0
* Add rcc_aclk and use for flash wait state calculations. Closes #120

Use rcc_aclk for flash wait state calculations

---

examples/README.md
examples/adc12.rs
examples/blinky.rs
examples/blinky_random.rs
examples/blinky_timer.rs
examples/dac.rs
examples/fractional-pll.rs
examples/mco.rs
examples/prec_kernel_clocks.rs
examples/pwm.rs
examples/qspi.rs
examples/rcc.rs
examples/sai_pdm.rs
examples/sdmmc.rs
examples/serial.rs
examples/spi.rs
examples/temperature.rs
examples/utilities/logger.rs
examples/vos0.rs

ITM logging as added by PR #107
`stm32::CorePeripherals::take()` ([re-exported here](https://github.com/stm32-rs/stm32-rs-nightlies/blob/master/stm32h7/src/stm32h743v/mod.rs#L701)) will only return `Some` once.
Use `steal()` instead, and assume the user won't try to access the ITM
peripheral from any of the examples.

examples: fix for ITM logging in examples that use CorePeripherals

---

src/time.rs

Operations like specifying timer dead time or pulse width or time delay
make more sense as times rather than frequencies. These time durations
can be measured in (tens or hundreds of) nanoseconds, so it makes sense
to have units to specify durations or delays measured in ns or us.
This PR only adds MicroSeconds and NanoSeconds and conversions between
them and MilliSeconds. I would like to have the 'advanced' timer functions
I'm working on take NanoSeconds as a parameter.

Added time types for microseconds and nanoseconds

---

src/gpio.rs
src/i2c.rs
src/pwr.rs
src/qspi.rs
src/sai/mod.rs
src/serial.rs
src/spi.rs

I was annoyed when an enum didn't impl Copy so I decided to add these impls to all enums that could use them. I chose `Copy, Clone, PartialEq` since I thought those would be uncontroversial. `Debug` could be useful as well, and some of the enums already impl it, but having lots of `Debug` impls slows compile times and bloats binaries. I didn't add impls to error types since maybe they might want to include some information which would conflict with the impls.

Impl Copy, Clone, PartialEq for enums

---

Cargo.toml
examples/tick_timer.rs
src/timer.rs

I want to be able to create a timer which counts up at a specific frequency.  I think this solution is pretty good.
It's a bit awkward since the existing constructors and methods are built around the reload-overflow timer, but the HAL makes it be that way. I can foresee confusion if someone creates a tick_timer than calls `start` or `wait` on it.
I thought about creating a separate timer type for this, we already do for `Pwm`, but it seems silly to duplicate 80% of that code just so we can configure the timer slightly differently.
Perhaps an overhaul of the timer system is in order, but I don't have the energy for that right now.

Timer: Allow configuring tick frequency

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Cargo.toml
examples/usb_passthrough.rs
examples/usb_serial.rs
src/lib.rs
src/rcc/rec.rs
src/usb_hs.rs

The examples require release mode to run correctly.
~~Blocked on:~~
* ~~https://github.com/stm32-rs/synopsys-usb-otg/pull/4~~
* ~~https://github.com/stm32-rs/stm32-rs/pull/401~~
* ~~https://github.com/stm32-rs/stm32h7xx-hal/pull/103~~
There are actually two USB peripherals:
| Name | Type | Base Address | Pin Name
| --- | --- | --- | --- 
| `OTG1_HS` | HS | 0x4004_0000 | `OTG_HS`
| `OTG2_HS` | HS | 0x4008_0000 | `OTG_FS`
~~This PR only adds support for `OTG1_HS`. [synopsys-usb-otg](https://github.com/stm32-rs/synopsys-usb-otg) could support `OTG2_HS` too, except it currently hard-codes the base address (0x4004_0000). It would be interesting to see if this could be fixed with no runtime cost by adding a `const fn` to the `UsbPeripheral` trait. If anyone is interested in picking this up I …

Add USB and example

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Cargo.toml
examples/rtc.rs
src/lib.rs
src/pwr.rs
src/rcc/backup.rs
src/rcc/core_clocks.rs
src/rcc/mod.rs
src/rtc.rs
src/time.rs

The RTC is a bit strange due to the backup power domain. I tried varying amounts of integration with the standard RCC, REC, PWR methods, but the implementation and semantics conflicted. Instead I added `Backup` to manage the backup power domain. Right now it's just the RTC but hypothetically it could help manage the backup SRAM and the LSE.
~~I started out with a minimal `Date`/`Time` implementation but found myself implementing more and more functionality so I replaced it with the `time` crate. It has a `no_std` mode but always requires an allocator. This isn't an issue for me but I might re-introduce the simple `Date`/`Time` and maybe genericize functions that take one of those as an argument.~~
I moved to the `chrono` crate since it doesn't require allocation.
Interested in any …

Implement RTC

---

.gitignore
Cargo.toml
examples/sai-i2s-passthru.rs
src/dma.rs
src/lib.rs
src/sai/i2s.rs
src/sai/mod.rs
src/traits/i2s.rs
src/traits/mod.rs

Implemented I2S for SAI1-4.
Added traits to split DMA channels.
Example runs on daisy seed board successfully.
Closes #90

Sai i2s v0.2.x 1

---

examples/rtic_low_power.rs
src/rcc/mod.rs
src/rcc/rec.rs
src/timer.rs

Actually quite a simple addition. This method could be added to the `ResetEnable` trait, but since it is intended for the user and not the HAL, I haven't done this.
Also implement LPTIM[1-5] and add an example that uses this.
* Breaking change to the type of TimerExt (but hopefully no-one was using that).
* Removes `ResetEnable` implementation for HSEM as this doesn't support any low power modes (somewhat obviously), but HSEM needs more consideration anyhow (particularly for dual-core parts).
Blocked on:
* https://github.com/stm32-rs/stm32-rs/pull/404

Add low_power method to PREC structure

---

src/lib.rs

Sometimes we need access to the `stm32h7::generic::Variant` enum type when working with hal methods like:
`pub fn get_kernel_clk_mux(&self) -> Variant<u8, Sai1ClkSel>`
For example:
```
use hal::rcc::rec::Sai1ClkSel; 
use hal::Variant::Val; 
match rec.get_kernel_clk_mux() {
Val(Sai1ClkSel::PLL1_Q) => clocks.pll1_q_ck(),
Val(Sai1ClkSel::PLL2_P) => clocks.pll2_p_ck(),
Val(Sai1ClkSel::PLL3_P) => clocks.pll3_p_ck(),
Val(Sai1ClkSel::I2S_CKIN) => unimplemented!(),
Val(Sai1ClkSel::PER) => clocks.per_ck(),
_ => unreachable!(),
}
```

Re-export stm32h7::generic::Variant

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
CHANGELOG.md
Cargo.toml
examples/ethernet-nucleo-h743zi2.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/ethernet-stm32h747i-disco.rs
src/ethernet/eth.rs
src/ethernet/ksz8081r.rs
src/ethernet/lan8742a.rs
src/ethernet/mod.rs
src/lib.rs

This is a breaking change, because the call to `new_unchecked` no longer resets and initialises the PHY. Now the user has to do that themselves.
* Keep the existing LAN8742A and KSZ8081R implementations available to use
* Add a builder method `set_phy_address` to configure the SMI address for the PHY

ethernet: Remove phy feature flags, allow user to implement their own PHY

---

src/dma/dma.rs
src/dma/macros.rs

This PR updates the DMA macro for SPI types. When SPI is configured for various transaction sizes, the `TargetAddress` needs to have a different associated `MemSize` so that the SPI peripheral can be used by DMA.

Updating DMA macro for SPI types

---

src/spi.rs

This PR fixes #158 by correcting the usage of the SPI management bits.
This PR fixes #71 by working around "endless transaction mode" by allowing more control of the way CS is managed.
This PR also exposes methods to allow SPI to be used in tx-only and rx-only configurations. It also allows for CS to automatically be idled when no data is available in the FIFO for transmission.

Updating SPI CS management

---

src/qspi.rs

This PR fixes #160 by updating the QSPI to read on clock falling edges instead of rising edges. This is a workaround to signal contention discovered on the QSPI bus. 
Refer to https://github.com/quartiq/stabilizer/issues/101 for evidence of signal contention that prompted this change

Updating QSPI to sample on falling edges

---

Cargo.toml
examples/digital_read.rs
examples/exti_interrupt.rs
examples/spi-dma-rtic.rs
src/qspi.rs
src/spi.rs

This PR adds in an `example/spi-dma-rtic.rs` example that demonstrates how to use RTIC, DMA transfers, and SPi together.
I also did a merge of `master` to gain access to the spi transmit-only functionality for the example.

[DMA] Adding DMA+SPI+RTIC example

---

Cargo.toml

Since [*Dependencies are resolved with the union of all features enabled on them*](https://doc.rust-lang.org/cargo/reference/resolver.html#features), it's good practice to remove unnecessary dependencies.
More features are added by the dev-dependency so that the examples build

Reduce smoltcp dependency features to a minimum

---

src/dma/mod.rs

This PR updates the DMA `next_transfer` to return the number of data that was not transferred. This is necessary for applications that are cancelled prematurely (e.g. in scatter-gather implementations where we gather as many data as possible in a fixed amount of time).

[DMA] Next transfer returns number of remaining data

---

src/dma/bdma.rs
src/dma/dma.rs
src/dma/macros.rs
src/dma/mod.rs
src/dma/traits.rs

This PR (into the `dma` branch) rewrites the `next_transfer()` and `next_transfer_with()` implementations.
* `CurrentBuffer` enums renamed to be more accurate and peripheral-matching.
* Added a few stream methods to expose the dbm/ct bits in joint semantics (also faster).
* Using `usize` for the addresses instead of `u32`.
* The non-double buffer and the double buffer code paths are unified.
* It poisons the inactive buffer address to convert silent corruption into DMA/bus errors (@adamgreig 's idea).
* With that, I'd consider `next_transfer_with()` `safe`. It's not DMA overrun safe in general but it is safe from any concurrent buffer access by user and DMA since the buffer the user has access to is always out of reach of the DMA (by poisoning or implicit disable). Certainly safe in the …

DMA buffer swap logic

---

examples/dma.rs
examples/i2c4_bdma.rs
examples/sai_dma_passthru.rs
examples/spi-dma-rtic.rs
examples/spi-dma.rs
src/dma/mod.rs

The lack of support for constant source buffers was first raised by @ryan-summers here https://github.com/stm32-rs/stm32h7xx-hal/pull/153#discussion_r515865869
This solution adds a 5th generic type parameter to `Transfer`, and uses this to implement `Transfer` for two different type constraints on `BUF`.
The additional generic type parameter will also be useful for MDMA support, which will also need its own versions of `init`, `next_transfer`, `next_transfer_with` and so on.
The downside is the additional complexity of another type parameter.

Implement DMA for constant source buffers

---

CHANGELOG.md
Cargo.toml
README.md
RELEASING.md

This PR merges `master` back into `dma` so that we can get the smoltcp updates into `dma` as well.
As an aside, it seems to me like we should probably merge `dma` in to master - I'm fairly sure a lot of people are essentially treating `dma` _as_ `master` to get access to DMA transfers right now. Curious to hear thoughts here

Updating smoltcp on DMA branch

---

examples/exti_interrupt.rs
examples/rtic.rs
examples/rtic_low_power.rs
src/gpio.rs

ref: [l4xx](https://github.com/stm32-rs/stm32l4xx-hal/pull/187), [f1xx](https://github.com/stm32-rs/stm32f1xx-hal/pull/303), [f4xx](https://github.com/stm32-rs/stm32f4xx-hal/pull/250), [f7xx](https://github.com/stm32-rs/stm32f7xx-hal/pull/111)

Use CamelCase for gpio::Edge enum variants

---

.github/workflows/clippy.yml
Cargo.toml
examples/dma.rs
examples/fmc.rs
examples/fractional-pll.rs
examples/i2c4_bdma.rs
examples/mco.rs
examples/prec_kernel_clocks.rs
examples/pwm.rs
examples/rcc.rs
examples/sdmmc.rs
examples/spi-dma.rs
examples/vos0.rs
examples/watchdog.rs
src/usb_hs.rs

Tested with an STM32H743BIT6 and a USB3300-EZK on a custom board.

USB: Add support for external ULPI PHYs

---

src/qspi.rs

* Bus width (but the `configure_mode` method can also be used)
* Address size (8/16/24/32-bit)
* Number of dummy cycles
* Sample on rising or falling edge
The configuration structure replaces the frequency argument in the constructors, but backwards compatibility is maintained with an Into<Config> implementation.

[qspi] Add hardware configuration structure

---

examples/adc12.rs
examples/ethernet-nucleo-h743zi2.rs
examples/sdmmc.rs
src/adc.rs
src/delay.rs
src/ethernet/eth.rs
src/ethernet/ksz8081r.rs
src/i2c.rs
src/rcc/pll.rs
src/serial.rs
src/spi.rs
src/timer.rs
src/traits/i2s.rs

Using `#[non_exhaustive]` breaks pre-1.40 support, that's acceptable at this point

Tidy various clippy lints

---

src/dma/bdma.rs
src/dma/dma.rs
src/ethernet/eth.rs
src/exti.rs
src/gpio.rs
src/i2c.rs
src/qspi.rs
src/rtc.rs
src/sai/i2s.rs
src/sai/mod.rs
src/serial.rs
src/spi.rs
src/timer.rs

If you clear an interrupt flag and quickly return from the interrupt, the interrupt will often immediately execute again. There are two possible causes for this:
1. The peripheral bus that executes the interrupt clear operation is clocked slower than the CPU clock, so there are a few instructions that are executed after clearing the IRQ flag but before the write takes effect.
2. The instruction pipeline may be executing future instructions that haven't 'noticed' the changed interrupt flag.
Adding the appropriate barrier instructions ensures that the side effects of the register write occur before the program continues executing.
See ARM Application Note 321.
Fixes #190

Add barriers to interrupt clearing functions

---

src/watchdog.rs

Tested it and it works. It follows the same interrupt pattern and names as the RTC.
It took me a while to test because the PAC/SVD has an error it where it says there are only 2 prescaler bits. I was wondering why the timeout came so quickly... :P
I'm fixing that here: https://github.com/stm32-rs/stm32-rs/pull/502

Added interrupt for wwdg

---

src/dma/bdma.rs
src/dma/dma.rs
src/ethernet/eth.rs
src/exti.rs
src/gpio.rs
src/i2c.rs
src/qspi.rs
src/sai/i2s.rs
src/sai/mod.rs
src/serial.rs
src/spi.rs
src/timer.rs

If the interrupt pending flag is set quickly multiple times it could be set after the pending flag is cleared but before the clear could be read by the busy wait loop, causing it to loop forever waiting for the pending flag to be cleared again.

Use register reads to delay peripheral interrupt clearing

---

src/ethernet/eth.rs

There is no gain from disabling interrupts between the memory barriers
and writing to the DMA engine descriptor ring pointers - even if an
interrupt is executed between the barrier and the atomic store to the
pointer, it doesn't make the descriptors any less valid.
Interrupts are also irrelevant for transmit/receive ring initialisation,
which needs to run wiht the DMA engine disabled anyway.
GitHub: Fixes #197.

Ethernet: Remove extraneous interrupt-free regions

---

Cargo.toml
examples/crc.rs
src/crc.rs
src/lib.rs
src/prelude.rs

This PR adds support for the hardware CRC unit. In addition to the hardware features, this adds automatic output XOR with a user-configured value; many CRC algorithms use an all-1 XOR and a few use a bit pattern XOR.
Tested on an STM32H750VBT6 and an STM32H743VIT6.

Add support for CRC unit

---

CHANGELOG.md
examples/usb_passthrough.rs
examples/usb_serial.rs
src/usb_hs.rs

Breaking change on the USB API, since the structure no longer contains instances of the pin types

Add new/new_unchecked methods for USB structures

---

README.md

This pull request updates the README.md file to add links to board support packages for the NUCLEO-H745ZI and Daisy Seed boards.

Add link to BSP's for NUCLEO-H743ZI and Daisy Seed

---

src/timer.rs

Ran into an issue where my devices would crash randomly.
I've dug around and found that when the set_timeout_ticks function gets a ticks value of an exact multiple of 2^16, it will overflow.
Also when `ticks > u32::MAX - u16::MAX`, the `+1` would overflow. I think it was tried to do it in 32 bit, but the parentheses were wrong.
This solves those issues. All psc and arr values remain the same with this change, except that there should be no panics anymore and all ticks values are valid.

Better calculations for set_timeout_ticks

---

src/serial.rs

This enables using the `write!` and `writeln!` macros on the full serial
struct. Previously, you would have to `.split()` the full serial struct
and extract the `Tx<USART>` component. (Which remains possible.)

implement fmt::Write for Serial<USART>

---

src/adc.rs

This was lost in db96799ead2de478cc5ca41bc6d78e62cbb27381.

add free for adc12

---

examples/spi_hardware_cs.rs
examples/spi_send_frames.rs
src/spi.rs

The hardware CS now comes in 4 specific modes that are setup in the config:
- Disabled
- EndlessTransaction
- WordTransaction
- FrameTransaction
New here is the frame transaction where `TSIZE` is used to send frames of a specific length.
There's now also `end_transaction` that is useful for endless and mandatory for frame transactions.
The blocking implementation now checks if we're in frame mode and will send frames when we are.
I don't have a nice dev board, so all testing was with an oscilloscope with the probe manually held to the pins. So I couldn't check everything as good as I'd like, but it should all work from what I could see.

Extended SPI with more hardware CS features

---

src/dma/bdma.rs
src/dma/dma.rs
src/dma/mod.rs
src/dma/traits.rs

When handling multiple double-buffered DMA streams the current safe-and-universal API becomes slower than necessary.
This adds `next_dbm_transfer_with()`, a closure-based API to the inactive buffer, without address poisoning, compiler fences, data barriers, or buffer swapping. For some applications this reduces the overhead significantly (speedup of 5).

Fast double-buffered DMA

---

src/dma/dma.rs

Don't reset the peripheral in the DMA1/2 StreamsTuple::new method

---

examples/ethernet-nucleo-h743zi2.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/ethernet-stm32h747i-disco.rs
examples/fmc.rs

The cortex-m [enable_icache](https://github.com/rust-embedded/cortex-m/blob/master/src/peripheral/scb.rs#L328) method already invalidates before enabling (and is guaranteed to do so in the docs too).

Remove explicit invalidate_icache from examples

---

.github/workflows/clippy.yml
CHANGELOG.md
examples/sai-i2s-passthru.rs
examples/sai_dma_passthru.rs
src/delay.rs
src/dma/mod.rs
src/dma/traits.rs
src/gpio.rs
src/pwm.rs
src/rng.rs
src/sai/i2s.rs
src/sai/mod.rs
src/sai/pdm.rs
src/spi.rs
src/time.rs

This PR removes a variety of clippy lints.
Notable changes:
* Time conversion now implements more traits (preferring From over Into)
* I2S constructor now uses a combination type to take less arguments
* Lint warnings are now elevated to failure in CI

Removing various clippy lints

---

src/gpio.rs

This PR implements the InputPin trait for Alternate-mode GPIO pins, allowing them to be read. This is just copying the implementation from Output and Input pins. There are no side effects to this atomic read, so this is safe to add, regardless of the alternate use of the pin.

Adding implementation of InputPin trait for Alternate function GPIO pins

---

CHANGELOG.md
examples/temperature.rs
src/signature.rs

Takes some inspiration from the [stm32-device-signature](https://crates.io/crates/stm32-device-signature) crate.
Avoids reading 32 additional bits above the signature value. Fixes #206

Simplify device signature API

---

src/crc.rs

The only one that has any significant effect is Config's `reflect` since it's now usable when you're making a const Config.

Make more CRC methods const

---

src/ethernet/eth.rs

The MACA0LR/HR registers hold the address the MAC can use for filtering received packets, but they're only loaded into the MAC core when LR is written to. Currently the ethernet driver writes to LR first and then HR, so the MAC core doesn't get the bits from HR, which breaks filtering. I believe that's why the RA (receive-all) bit has been set, which bypasses the filtering.
This PR fixes writing the MAC address and disables the no-longer-required RA bit.
I've tested this with an H745 nucleo board and the ethernet-rtic-stm32h747i-disco example, changing just the GPIO setup to match the Nucleo.
See also https://github.com/embassy-rs/embassy/pull/389.

Ethernet: Disable RA in filtering, fix MAC address setting

---

CHANGELOG.md
examples/adc12.rs
examples/adc12_parallel.rs
examples/temperature.rs
src/adc.rs

This patch splits the current `convert()` method of ADC in two public methods: `start_conversion()` and `read_sample()`. With this, it is now possible to start conversion on multiple ADCs at the same time and then collect results.
There is one issue I'm not sure how to solve - I can call `start_conversion` on one channel and then `read_sample` on another and it would successfully read something. I suppose it would be better to protect user by exploding in case two channels are mixed. Thoughts?

Allow parallel conversion on multiple ADCs

---

CHANGELOG.md

This change has broken all existing calls to the constructor.
https://github.com/stm32-rs/stm32h7xx-hal/commit/6768a6f4ba9b2abf477851996679819256945593
Signed-off-by: Petr Horacek <hrck@protonmail.com>

Mark change to I2S constructor as breaking

---

CHANGELOG.md
Cargo.toml
examples/i2c4_bdma.rs
examples/rtic_low_power.rs
src/adc.rs
src/crc.rs
src/dma/bdma.rs
src/lib.rs
src/ltdc.rs
src/pwr.rs
src/rcc/backup.rs
src/rcc/mod.rs
src/rcc/rec.rs
src/sai/i2s.rs
src/sai/mod.rs
src/serial.rs
src/spi.rs
src/timer.rs
src/watchdog.rs

* ~RTIC v0.5 is no longer supported since the PAC does not implement `Nr` trait for Interrupts~
* RCC registers have been renamed for RM0455 parts
* PAC `Variant::Val<T>` replaced with `Option<T>`

Update to stm32-rs v0.14.0

---

Cargo.toml
examples/sdmmc_fat.rs
src/sdmmc.rs

It would have been nice to implement `embedded:BlockDevice` directly on `Sdmmc<$SDMMCX>` but that is not possible since `BlockDevice` takes `&self` and the methods that already exist take `&mut self`.

Add glue to make embedded-sdmmc work nicely

---

examples/serial-advanced.rs
src/serial.rs

Follow on from #261 
* Add synchronous flag to serial_unchecked method
* Set synchronous bits on USART peripherals only, for others they are reserved
* Add builder methods for USART configuration fields
* Add an example of synchronous USART operation

USART additions

---

CHANGELOG.md
examples/ethernet-nucleo-h743zi2.rs
examples/ethernet-rtic-stm32h735g-dk.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/ethernet-stm32h747i-disco.rs
src/ethernet/eth.rs

This allows users to decide how many transmit and receive buffers they wish to have the the `ethernet::DesRing`. Typically this allows a trade-off in performance vs memory usage.
The number of buffers need to be annotated on both `ethernet::DesRing` and `ethernet::EthernetDMA`. Requiring it on both is a slight usability downside. However this is small compared to the previous solution, which was making a local copy of the HAL in order to edit a constant value in `src/ethernet/eth.rs`.

Make ethernet::DesRing generic over the number of buffers

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
CHANGELOG.md
Cargo.toml
examples/octospi.rs
examples/qspi.rs
examples/qspi_mdma.rs
src/dma/mdma.rs
src/lib.rs
src/prelude.rs
src/xspi/mod.rs
src/xspi/octospi.rs
src/xspi/qspi.rs

`write_extended` and `read_extended` methods allow more complicated transactions, such as those needed to read/write from flash memories.
Rename the `quadspi` flag to `xspi`
Ref #165

Initial OCTOSPI and QUADSPI memories support

---

Cargo.toml
src/gpio.rs

Implements the IoPin trait from embedded-hal.

Implement IoPin

---

src/dma/macros.rs
src/prelude.rs
src/spi.rs

SPIs didn't have proper traits, so it was hard/impossible to be generic overall SPis.
- Added `SpiEnabledExt` for enabled SPIs
- Added `SpiDisabledExt` for disabled SPIs
- Added `SpiAllExt` which `SpiEnabledExt` and `SpiDisabledExt` must implement.
- These changes are breaking as people previously using the Spi will need to `use Spi{Enabled,Disabled,All}Ext`. We could also make the traits delegate to the previously existing implementations, but this might not be as clean in terms of hal code imo—and the version is `< 1.x.y` anyway. Thoughts?

add spi traits

---

examples/README.md

I think it makes more sense to give users instructions on how to  build the example applications in their own binary crate. This is how some other HAL crates did it. This PR restructures the `README.md` file a bit and provides complete instructions on how to create a new binary crate and build the blinky example in it.

Example README update

---

CHANGELOG.md
Cargo.toml

The stm32h7 crate includes 'rt' as a default feature for 0.14.0: https://docs.rs/crate/stm32h7/0.14.0/source/Cargo.toml

Fix the rt feature for stm32h7 0.14.0

---

src/dma/macros.rs
src/prelude.rs
src/spi.rs

- rename to SPI traits to possibly better names
-  `SpiAll` -> `HalSpi`
- `SpiEnabled` -> `HalEnabledSpi`
- `SpiDisabled` -> `HalDisabledSpi`
- `reset` no longer needs to take ownership of the given SPI peripheral

improve spi traits

---

Cargo.toml
examples/ethernet-rtic-stm32h735g-dk.rs
examples/ethernet-rtic-stm32h747i-disco.rs

Changelog: https://github.com/smoltcp-rs/smoltcp/blob/v0.8.0/CHANGELOG.md
Tested DHCP & TCP with a STM32H743 nucleo board, still works.

update smoltcp from 0.7.0 to 0.8.0

---

CHANGELOG.md
src/adc.rs
src/fmc.rs
src/pwm.rs
src/rng.rs
src/sai/i2s.rs
src/sai/mod.rs
src/sai/pdm.rs
src/sdmmc.rs
src/serial.rs
src/spi.rs
src/timer.rs
src/xspi/mod.rs
src/xspi/octospi.rs
src/xspi/qspi.rs

* More helpful panic messages that name the consumer and the stopped clock
* Expose more of these methods in the public API
* Standardise around `kernel_clk`/`kernel_clk_unwrap` naming (excluding timers)

Improve error diagnostics when kernel clocks are stopped

---

CHANGELOG.md
src/serial.rs

The first commit documents how serial data word length and parity are related.
The second commit removes manual control over serial data word length but configures it automatically based on the parity. This seems reasonable to do since we only support reading/writing 8-bit data.
closes #296

serial: document parity and word length configuration, set word length based on parity

---

examples/usb_passthrough.rs
examples/usb_serial.rs

This was fixed in usb-device: https://github.com/mvirkkunen/usb-device/pull/41

remove release mode requirement from USB examples

---

.github/workflows/ci.yml
Cargo.toml
src/adc.rs
src/crc.rs
src/dma/bdma.rs
src/dma/dma.rs
src/dma/mdma.rs
src/dma/mod.rs
src/i2c.rs
src/lib.rs
src/pwm.rs
src/rng.rs
src/rtc.rs
src/sai/i2s.rs
src/sdmmc.rs
src/serial.rs
src/spi.rs
src/time.rs
src/timer.rs
src/xspi/mod.rs

> `defmt` ("de format", short for "deferred formatting") is a highly efficient logging framework that targets resource-constrained devices, like microcontrollers.
https://defmt.ferrous-systems.com/
I've been maintaining this support in my fork for some time, it hasn't been burdensome. defmt has become popular enough that I think it is worthwhile to upstream this. Supporting defmt formatting in this library makes it easier to print error messages (don't need to use `defmt::Debug2Format`) and eliminates the code bloat of the `core::fmt` machinery. We could similarly move `Debug` derives behind a feature flag to help people who are trying to eliminate `core::fmt`, but I don't particularly care.

Add optional support for printing some types with defmt

---

Cargo.toml

The crate completely fails to build without this feature, remove it so that trying to build with --no-default-features gives a useful error message

Always enable the embedded-hal/unproven feature

---

src/pwm.rs

PD12 is linked to TIM4 via AF2

---

Cargo.toml
examples/flash.rs
src/flash.rs

Hello, I've spent some time [implementing flash](https://github.com/stm32-rs/stm32h7xx-hal/issues/281) read/write/erase functions for the stm32h743. 
The current limitations of the implementation are:
- rm0433 devices supported only
- "Simple" mode operations only (No secure flash operations)
- AXI clock speed is not yet configured / optimized
But I think this could be a good start, ideally I'll also get the AXI clock configured but I'm running out of time.
As this is my first contribution I would love any feedback for improvements.
Thanks very much

Flash implementation for rm0433

---

CHANGELOG.md
src/spi.rs

Duplex failed errors occour when a word was sent, but no corresponding word was received
* Refactor `byte` -> `word` since this is implemented for 8, 16 and 32 bits
* Make long transactions slightly more efficient by not writing CSTART after the
4th word and only reading SR once per word (rather than twice)
* Fix arithmetic error in spi divider calculation

SPI: Error on DuplexFailed errors 

---

Cargo.toml
src/rcc/mod.rs

I'm thinking about how to implement RCC debug prints https://github.com/stm32-rs/stm32h7xx-hal/issues/314 in the cleanest fashion. 
There is a lot going on in the RCC setup and a complete feedback about all the exact register settings is a substantial amount of information that is not easily made human readable. 
I think what would make sense is to give feedback corresponding to the Clock Configuration in CubeMX:
That would be all the MUX settings, prescalers, dividers and the PLL-frac.
I could have one compact codeblock at the end of the freeze function where I read the necessary registers again and give the formatted debug info (currently its just printing raw reg bits). 
https://github.com/stm32-rs/stm32h7xx-hal/blob/d924165915c74f34e8b1610934afc20e133b10e5/src/rcc/mod.rs#L976-L977
The …

RCC debug prints

---

examples/sai_dma_passthru.rs
src/dma/dma.rs
src/prelude.rs
src/sai/dma.rs
src/sai/mod.rs

Implement as wrapper type instead, which allows us to pretend this is a smart pointer type and make use of [deref coercion](https://doc.rust-lang.org/std/ops/trait.Deref.html)
This is actually backwards compatible, so the old fixed mapping (write on channel A, read on channel B) still works

Prototype of implementing SAI DMA on ChannelA/B compound types

---

CHANGELOG.md
src/lib.rs
src/sai/pdm.rs
src/serial.rs

There's only a few remaining uses of crate::Never

Replace crate::Never with core::convert::Infallible

---

examples/serial-inverted-loopback.rs
src/serial.rs

This allows the USART's to be used with serial devices that have inverted logic levels. I also added an example just for a proof of concept. I have tested the example with a NUCLEO-H723ZG board and have successfully used invertrx to receive an sbus serial signal from a Frysky RX4R RC receiver.

Add invertrx and inverttx to serial::config::Config

---

CHANGELOG.md
examples/prec_kernel_clocks.rs
src/adc.rs
src/dac.rs
src/dma/bdma.rs
src/dma/dma.rs
src/dma/mdma.rs
src/i2c.rs
src/pwm.rs
src/pwr.rs
src/qei.rs
src/rcc/mco.rs
src/rcc/mod.rs
src/rcc/rec.rs
src/sai/i2s.rs
src/sai/mod.rs
src/serial.rs
src/spi.rs
src/timer.rs

Use of this attribute was [expanded in the standard library](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#more-must_use-in-the-standard-library) in Rust 1.58, and there is now a [clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use[](https://github.com/richardeoin)).
Silence the lint for REC methods, since dropping the REC is intended.
Also silence the lint for GPIO modifiers (set_speed) since these are also often dropped.

Add #[must_use] annotations

---

examples/adc.rs
examples/adc12_parallel.rs
src/adc.rs

Add slope method to ADC and depreciate max_sample

---

src/gpio.rs
src/gpio/convert.rs

With the new GPIO API it is not possible anymore to create a generic
functions that would turn a Pin into PushPull unless the current mode of
the Pin is hardcoded.
This used to work:
```
pub struct LedUser(pub gpio::gpioc::PC7<gpio::Output<gpio::PushPull>>);
impl LedUser {
pub fn new<Mode>(pin: gpio::gpioc::PC7<Mode>) -> Self {
LedUser(pin.into_push_pull_output())
}
}
```
Now it fails due to:
```
error[E0599]: the method `into_push_pull_output` exists for struct `stm32h7xx_hal::gpio::Pin<'C', 7_u8, Mode>`, but its trait bounds were not satisfied
--> src/led.rs:29:21
|
29 |         LedUser(pin.into_push_pull_output())
|                     ^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `stm32h7xx_hal::gpio::Pin<'C', 7_u8, Mode>` due to unsatisfied trait bounds                
|
= note: …
```

Expose PinMode as public

---

examples/gpio_with_input.rs
src/gpio/convert.rs

Previously when resetting it would assume the pin was in the ORIG pin mode and try to convert it to the ORIG pin mode, which the if statements in mode blocked. Now by tracking the witness pin and the original MODE the reset can properly set the mode register bits.
By fixing ResetMode it allows for the `with_<mode>` methods to work and set the MODER bits. Fixes #358.
Since I've fairly new to heavy generics and microcontroller level optimization, it would be really great if someone could double-check that this doesn't break anything the previous implementation upheld! Thank you!

Convert ResetMode to own witness pin and track past pin mode

---

src/flash.rs

Adjusts the visibility of various Flash `Bank` methods which will help users determine memory locations of sectors etc. 
For example if the user is writing a bootloader beginning at Bank 1, Sector 6, and they need to know the address to jump to, this will allow them easily.

fix: flash bank impl visibility

---

src/dma/bdma.rs
src/dma/dma.rs
src/dma/mdma.rs
src/dma/traits.rs

Make less use of macros, and more use of trait bounds. StreamX struct matches f4 API

Re-work DMA internals

---

src/flash.rs

Writing flash sectors fails after a couple of writes without waiting for the EOP flag in the FLASH_SR# register to go low after each write. The reference doesn't mention that this is necessary, but it fails without this on my STM32H743IIT6 devboard.

Fix intermittent flash programming error.

---

CHANGELOG.md
Cargo.toml
src/flash.rs

Currently, the flash driver doesn't correctly split data into 256 bit chunks when writing. This PR fixes that as well as fixes error handing around flash operations and adds more expressive flash errors.

Write flash in 256-bit chunks correctly

---

src/flash.rs

The check was accidentally done with the bit size instead of the byte size.
Later in the function the correct value of 32 is used in the chunks_exact function.

Correct flash word check

---

Cargo.toml
src/sdmmc.rs

Update sdio-host version and improve eMMC support

Update sdmmc support

---

CHANGELOG.md
src/flash.rs

Following from issue: https://github.com/stm32-rs/stm32h7xx-hal/issues/382
The following code in certain circumstances yields a `BankError::PROGRAMMING_SEQUENCE`:
```rust
let mut buffer: [u8; 256] = [0xFF; 256];
// ... fill buffer with data
flash.erase_sector(Bank::UserBank2, 7).unwrap();
flash
.write_sector(Bank::UserBank2, 7, 0, &buffer)
.unwrap();
```
Reading the PM0433 reference manual; 4.7.3:
```
Programming sequence error (PGSERR):
More specifically, PGSERR1/2 flag is set if one of below conditions is met:
• A write operation is requested but the program enable bit (PG1/2) has not been set in FLASH_CR1/2 register prior to the request.
• The inconsistency error (INCERR1/2) has not been cleared to 0 before requesting a new write operation.
```
**_Solution:_**
I've found that enabling …

flash: fence ordering to ensure pg bit is set before write to flash memory

---

CHANGELOG.md
src/pwm.rs

I can't find any sense `Polarity` to be part of channel type because it doesn't affect on what traits and methods can be implemented on type. So I've removed `ActionLow` and `ActionHigh` from type and added `set_polarity` and `set_comp_polarity` runtime methods.

Pwm channels cleanups

---

CHANGELOG.md
examples/adc.rs
examples/adc12.rs
examples/adc12_parallel.rs
examples/dac_adc.rs
examples/temperature.rs
src/adc.rs
src/pwr.rs

Use the prescaler to set the fastest ADC clock below or equal to this limit
Addresses #374 
TODO:
- ~Support CKMODE[1:0]~

Add initialization argument for ADC frequency

---

CHANGELOG.md
src/i2c.rs

Simply wait until the busy flag is released. Now the stop condition occurs (right before the next start condition in the case of successive writereads). 
Fixes #401

Bugfix for I2C transaction stop conditions

---

CHANGELOG.md
src/adc.rs
src/gpio.rs
src/sai/i2s.rs

- allows us to read any alternate pin
- no longer have to read `Alternate` registers manually
- I am not super familiar with the ref manual, so if anyone has any other thoughts/criticism I would love to hear.

make `Alternate` variants readable

---

src/rcc/pll.rs

Register fields are 7-bit.
Closes #406

Add bounds check on PLL R/Q dividers

---

.gitignore
.vscode/settings.json

- add VSC settings
- helps contributers be able to work out of the box
- currently `clippy` and `rust-analyzer` do not work out of the box

add VSC settings

---

Cargo.toml
src/xspi/octospi.rs

Minor fixes

---

Cargo.toml
src/lib.rs
src/prelude.rs
src/rcc/backup.rs
src/rng.rs
src/sdmmc.rs
src/usb_hs.rs

Uses docrs attributes to highlight items behind a feature flag. There's more info [here](https://users.rust-lang.org/t/how-to-document-optional-features-in-api-docs/64577)

Improve documentation rendering of feature flags

---

examples/serial-halfduplex.rs
src/serial.rs

This allows the USART's to be used with serial devices that operate in a half-duplex mode (transmit and receive on one wire). An example was also added (serial-halfduplex) and has been tested with a NUCLEO-H723ZG board. It has also been tested with a Frysky RX4R RC receiver Smart Port interface.

Add halfduplex to serial::config::Config and example

---

Cargo.toml
examples/sai_dma_passthru.rs

* Bump embedded-sdmmc from 0.4 to 0.5
* Bump fdcan from 0.1 to 0.2
* Bump embedded-graphics from 0.7 to 0.8
* Update [[example]] targets

Bump dependencies

---

src/ethernet/eth.rs

Revert the changes to `eth.rs` from #445 
Fixes #448

Revert "Move ethernet DMA reset slightly earlier to eliminate freeze on h723"

---

src/serial.rs
src/spi.rs
src/xspi/mod.rs

Specifically we cast `*const T` to `*const UnsafeCell<T>` then use the [`UnsafeCell::raw_get`](https://doc.rust-lang.org/stable/std/cell/struct.UnsafeCell.html#method.raw_get) method.

Replace casts of &T to &mut T with UnsafeCell

---

CHANGELOG.md
examples/sdmmc.rs
src/sdmmc.rs

`write_block` needs to be called for every 512 bytes long block that is to be written to the SD card. Each of these calls requires the overhead of negotiating the write command and if I understand it correctly it also requires to erase the whole SD segment and copying it back. 
With this patch, `write_blocks` is introduced, mirroring the behavior of `read_block` and `read_blocks`. This new method by itself helped me to improve write speed from the original example of 9.2 kB/s to 65 kB/s.
Write performance with 480 MHz system clock, 50 MHz bus speed, and enabled caches:
| Buffer size | Total size written | Speed |
| -- | -- | -- |
| 64 kB | 64 kB | 513 kB/s |
| 64 kB | 32 MB | 4.9 MB/s |
|128 kB | 32 MB | 5.2 MB/s |
Using ACMD23 to erase block data before writing in my case did not improve …

Introduce SDMMC `write_blocks`

---

CHANGELOG.md
examples/sdmmc_fat.rs
src/sdmmc.rs

With this patch, the FAT write binding would use sdmmc CMD25 to write blocks of data.
It also extends the FAT example so it exercises both `write_block` and `write_blocks`.

Utilize write_blocks in FAT binding 

---

src/sdmmc.rs

I spotted this when looking at the recent changes to this file.

fix typo in sdmmc.rs

---

CHANGELOG.md
examples/usb_rtic.rs
src/usb_hs.rs

See pinouts in part datasheets. To use these pins for USB, it's not necessary to switch them to an alternate function: the USB D-/D+ pins are functional when the GPIO state is Analog. Tested on a STM32H7A3ZIT6
The ability to allocate PA11/PA12 to AF10 was correctly removed in https://github.com/stm32-rs/stm32h7xx-hal/pull/346 , but this exposed the bug.

usb: On rm0455/rm0468 parts, pins PA11/PA12 do not have an alternate function for USB

---

src/xspi/mod.rs
src/xspi/qspi.rs

Hi, I'm using this library with a STM32 H7 series microcontroller which is connected to a NOR Flash with 2 chips.
Since this NOR Flash support QuadSPI, I wanted to use it but I also want to access to both memory chips.    
Since Both of my flash chips are used separatly, one for image backup and one for temporary storage, I want to access to only one of them at a time.    
My problem is that, when I looked at the Dual-Flash mode, it seems that I have to read and write to both chips at the same time as from the `Quad-SPI interface on STM32 microcontrollers and microprocessors` STM documentation, I can read:
> Note that all bytes at even addresses are stored in Flash 1 while all bytes at odd addresses are stored in Flash 2.
> As described in the figure above, in Dual-Flash mode the same …

Expose QSPI control register to switch used bank

---

CHANGELOG.md
Cargo.toml
examples/usb_passthrough.rs
examples/usb_phy_serial_interrupt.rs
examples/usb_rtic.rs
examples/usb_serial.rs
src/usb_hs.rs

This PR updates the various usb-* crates, which just got updated releases last week.

Updating usb crates

---

Cargo.toml
examples/blinky-stm32h747i-disco.rs

Add new blinky example using GPIOs on STM32H747i-Disco
- GPIO port : PI12 for LED1
- GPIO port : PI13 for LED2
- GPIO port : PI14 for LED3
- GPIO port : PI15 for LED4
by Youndong (youndong.park@gmail.com)

Add new blinky example using GPIOs on STM32H747i-Disco

---

examples/adc_dma.rs
examples/dma.rs
examples/ethernet-nucleo-h743zi2.rs
examples/ethernet-rtic-nucleo-h723zg.rs
examples/ethernet-rtic-stm32h735g-dk.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/ethernet-stm32h747i-disco.rs
examples/i2c4_bdma.rs
examples/mdma.rs
examples/mdma_bursts.rs
examples/sai_dma_passthru.rs
examples/sdmmc.rs
examples/serial-dma.rs
examples/spi-dma-rtic.rs
examples/spi-dma.rs
examples/usb_passthrough.rs
examples/usb_phy_serial_interrupt.rs
examples/usb_rtic.rs
examples/usb_serial.rs

[rust/#114447](https://github.com/rust-lang/rust/issues/114447) made `&mut MY_STATIC_MUT` a warning, with the intention of disallowing it entirely in the 2024 edition. We never used this in the crate itself, but it is used in many examples.
This commit removes these references from the examples. In general the new approach is to change `static mut` of type `X` to type `MaybeUninit<X>`. These can then cleanly be accessed with [`MY_STATIC_MUT.write()`](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html#method.write) followed by [`MY_STATIC_MUT.assume_init_mut()`](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html#method.assume_init_mut).
Where we need to cast a (reference to a)`MaybeUninit<[X; N]>` to a `[MaybeUninit<X>; N]` in order to initialise it element-by-element, the …

Remove references to `static mut`

---

Cargo.toml

Also remove extra "proto-ipv6" feature that is not needed by examples

Upgrade smoltcp to 0.11.0

---

examples/usb_phy_serial_interrupt.rs
src/crc.rs
src/ethernet/eth.rs
src/sai/i2s.rs
src/sai/pdm.rs
src/spi.rs
src/timer.rs

`TryFrom` and `TryInto` are part of the Rust prelude [since the 2021 edition](https://doc.rust-lang.org/edition-guide/rust-2021/prelude.html). https://github.com/stm32-rs/stm32h7xx-hal/pull/236

Tidy redundant imports

---

src/flash/mod.rs

This adds a `access_banks` helper to the `FlashExt`, which is a middle ground between `access_bank1` and `split`.
Right now the only way to access bank 2 is using the `split` method, which consumes the `FLASH` instance. In my usecase I want to access both flash banks but I also need to flip the banks at some point, so I need to have access to the option control register via [`FLASH::optcr(&self)`](https://docs.rs/stm32h7/0.15.1/stm32h7/stm32h743v/flash/struct.RegisterBlock.html#method.optcr), which needs the `FLASH` instance.
Using the new `access_banks` helper I can keep the `FLASH` instance around and get access to both banks as well as the option control register when I need it.

Add access_banks flash accessor

---

src/xspi/mod.rs
src/xspi/octospi.rs
src/xspi/qspi.rs

This adds `Config.modes` and `Xspi.configure_modes` methods but keeps the existing API (which sets the same mode for all phases).

Add support for using different modes for each phase of an xspi operation

---

src/timer.rs

STM32 timers, in upcounting mode, count from 0 to `ARR` (inclusive) before restarting at 0/generating an overflow event, so we need to subtract 1 from the number of desired ticks to get the correct period.

Fix off-by-one-tick in timer period calculation

---

src/ethernet/eth.rs

Fixing issue https://github.com/stm32-rs/stm32h7xx-hal/issues/507.

Fix eth::DesRing alignment

---

examples/dma.rs
examples/ethernet-nucleo-h743zi2.rs
examples/ethernet-rtic-nucleo-h723zg.rs
examples/ethernet-rtic-stm32h735g-dk.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/ethernet-stm32h747i-disco.rs
examples/i2c4_bdma.rs
examples/mdma.rs
examples/mdma_bursts.rs
examples/sai_dma_passthru.rs
examples/serial-dma.rs
examples/spi-dma-rtic.rs
examples/spi-dma.rs
examples/usb_passthrough.rs
examples/usb_phy_serial_interrupt.rs
examples/usb_rtic.rs
examples/usb_serial.rs
src/dsi.rs

Turned out to be more warnings that were drowned by the static mut errors

Fix more clippy warnings

---

CHANGELOG.md
Cargo.toml
examples/ethernet-rtic-nucleo-h723zg.rs
examples/ethernet-rtic-stm32h735g-dk.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/rtic.rs
examples/rtic_low_power.rs
examples/rtic_timers.rs
examples/sai-i2s-passthru.rs
examples/spi-dma-rtic.rs
examples/usb_rtic.rs

We don't implement anything RTIC-specific in the HAL itself and the examples use only basic RTIC functions. Therefore these changes are quite limited.
~Intend to merge sometime after v0.17 release~

Update examples to RTIC v2 framework
