Cargo.toml
examples/adc.rs
src/adc.rs
src/i2c.rs
src/lib.rs
src/rcc.rs

Adding the ADC implementation I finally got working yesterday together with an example for it. Furthermore I added @Jan561 as an author as he did most of the work on the ADC except solving a few issues with them. (I'm doing this PR instead of him as he's currently out on vacation)

Adding an ADC implementation

---

examples/blinky_random.rs
src/lib.rs
src/prelude.rs
src/rcc.rs
src/rng.rs

* From @dotcypress's `stm32g0xx-hal` with thanks
* Enable HSI48

rng: add implementation and example

---

examples/pwm.rs
src/lib.rs
src/prelude.rs
src/pwm.rs
src/rcc.rs
src/spi.rs
src/timer.rs

* Add `GetClk` trait and implementations in `timer.rs` to return a
timer's clock

pwm: implementation and example

---

Cargo.toml
README.md

Add some badges and a docs link to the README

v0.2.0, update README

---

src/i2c.rs

* Detect Not-Acknowledge as a separate error
* Clear error flags in the peripheral, so that it can be used for further transactions. For instance in the case of a Not-Acknowledge, it may be reasonable to repeat the transaction

i2c: detect not-acknowledge error, clear errors when detected

---

Cargo.toml
src/adc.rs
src/pwm.rs
src/rcc.rs
src/rng.rs
src/serial.rs
src/spi.rs
src/timer.rs

See [svd2rust changelog](https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#v0160---2019-08-05)

Upgrade to stm32-rs v0.9.0  (including svd2rust v0.16)

---

src/rcc.rs

rcc: pll2, pll3

---

src/i2c.rs

Without this, the state of the TXIS flag for the next transactions is
undefined.

i2c: flush the TXDR register when a NACK condition occurs

---

.travis.yml
Cargo.toml

Feature `stm32h757cm7` was merged with `stm32h747cm7`

Upgrade to stm32-rs v0.10.0

---

src/i2c.rs

- Use TXE to detect transmission finished in `write_read`
- Allow `busy_wait` to wait on variants of isr flags
- `busy_wait` returns immediately on success
- run rustfmt 
Tested with the following embedded hal i2c drivers:
- bmp280 (barometer)
- ssd1306 (oled display)
- bno080 (ahrs wip)

Fixes for i2c:

---

src/serial.rs

- Clear serial errors in ICR  after reading in serial::Read
- Implement marker trait to take advantage of blocking write_n implementation from embedded hal

Clear usart errors after reading, implement default blocking write 

---

.travis.yml
src/lib.rs
src/rcc.rs
src/rcc/core_clocks.rs
src/rcc/mod.rs
src/rcc/pll.rs
src/rng.rs

I'm not entirely sure cargo + travis can do this, but this is a first
attempt. The numerical behaviour of the host platform might not quite
correspond to the target.

Add some tests for RCC! These run on the host.

---

examples/spi.rs
src/spi.rs

Now requires type annotation / hinting somewhere

spi: Documentation, support 16-bit words also

---

src/i2c.rs
src/qei.rs
src/serial.rs
src/spi.rs

This PR fixes #65 by removing pin storage within device drivers, which also removes the pin type from the driver type. Additionally, it exposes an `unchecked` API that allows users to instantiate a driver without providing pins if they have complex requirements.
This addresses the following drivers:
* I2C
* SPI
* QEI
* UART
CC: @hargoniX @richardeoin

Erase pins from device driver types

---

Cargo.toml
src/rcc/rec.rs

MIPI-DSI present on 747/757 parts only, see
https://www.st.com/en/microcontrollers-microprocessors/stm32h7-series.html
Tidy TODO

Add feature gate and Reset / Enable for MIPI-DSI

---

examples/dac.rs
src/dac.rs
src/lib.rs
src/prelude.rs
src/traits/README.md
src/traits/dac.rs
src/traits/mod.rs

Implementation of a trait that is not in embedded-hal but is common to several of the
other stm32-rs crates

DAC implementation

---

.github/bors.toml
.github/workflows/ci.yml
.github/workflows/rustfmt.yml
README.md

Add nightly check, add cargo fmt

CI: Re-enable MSRV check after rtfm/rtic 0.5.1 -> 0.5.3

---

examples/mco.rs
src/rcc/core_clocks.rs
src/rcc/mco.rs
src/rcc/mod.rs

MCO = Micro-Controller Out pins, PA8 and PC9

Add support for MCO pins, also small improvements to rcc

---

src/i2c.rs

This is quite a tricky area but the previous version was flawed in several ways:
* The floating-point representation of `presc` was used for further calculation,
whilst the hardware divides by integers only.
* The `assert!` statements for out of range values of out-of-range values were
commented, probably because they were being hit regularly.
* Some almost-magic numbers (514, 387 ?)
The HAL now panics if the bus frequency is too slow to be achieved with the
maximum division ratio (8192). For a max(vos1) PCLK4 = 100MHz this corresponds
to a bus frequency of 12.2kHz. Previously it just set some other semi-random bus
frequency faster than specified.
It now asserts that the ratio between `i2cclk` and `freq` must be 4 or greater;
this is assumed by the standard-mode calculation.
The `SDADEL` …

i2c: Fix i2c bus clock frequency calculation

---

examples/adc.rs
examples/adc12.rs
examples/temperature.rs
src/adc.rs
src/rcc/rec.rs

Add method to initialise ADC1 and ADC2 together

---

src/rcc/mod.rs

Set sys_ck frequency to pll1_p_ck when this is used

---

.github/workflows/nightly.yml
Cargo.toml
examples/ITM.md
examples/README.md
examples/adc.rs
examples/adc12.rs
examples/blinky.rs
examples/blinky_random.rs
examples/blinky_timer.rs
examples/dac.rs
examples/fractional-pll.rs
examples/i2c.rs
examples/mco.rs
examples/prec_kernel_clocks.rs
examples/pwm.rs
examples/qspi.rs
examples/rcc.rs
examples/rtic.rs
examples/rtic_timers.rs
examples/sai_pdm.rs
examples/sdmmc.rs
examples/serial.rs
examples/spi.rs
examples/temperature.rs
examples/utilities/logger.rs
examples/vos0.rs
examples/watchdog.rs
src/lib.rs
src/logger.rs

Implemented logger that supports ITM, RTT, and semihosting.
Updated examples to use the log crate.
I have tested it with RTT and none.
Closes #104 
Closes #7

Implemented logger that supports ITM, RTT, and semihosting

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Cargo.toml
examples/fmc.rs
src/fmc.rs
src/lib.rs
src/prelude.rs

The [stm32-fmc](https://github.com/stm32-rs/stm32-fmc) crate is still a work in progress.
Todo:

Add FMC controller via stm32-fmc crate

---

src/rcc/mod.rs
src/rcc/rec.rs

* Fix small error in docs
* Refactor peripheral_reset_and_enable_control
* Add docs per-peripheral

Add generated docs for the PREC struct of each peripheral 

---

src/gpio.rs

A quick survey shows the other stm32-rs HALs vary on if they reset the gpio peripheral in the `split` call.
Enable, no Reset:
[f4](https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/gpio.rs#L274)
[f7](https://github.com/stm32-rs/stm32f7xx-hal/blob/master/src/gpio.rs#L123)
Enable and Reset:
[f1](https://github.com/stm32-rs/stm32f1xx-hal/blob/master/src/gpio.rs#L291)
[f3](https://github.com/stm32-rs/stm32f3xx-hal/blob/master/src/gpio.rs#L293)
[l4](https://github.com/stm32-rs/stm32l4xx-hal/blob/master/src/gpio.rs#L216)
I think offering both options is reasonable.

Add split_without_reset method to GPIO, and docs

---

examples/pwm.rs
src/pwm.rs

This was previously blocked on #134

Impl PwmPin for TIM12 - 17

---

examples/digital_read.rs
examples/exti_interrupt.rs

Some of the folks on the chat helped me out getting some hello world type stuff working this evening. Might as well open a PR with an extra example, in case this could help someone else out.
Thanks peeps

An example for EXTI interrupts

---

src/adc.rs
src/delay.rs
src/timer.rs

Add DelayFromCountDownTimer for when SYST is unavailable

---

examples/serial-dma.rs
src/dma/dma.rs
src/dma/macros.rs
src/serial.rs
src/spi.rs

Tested working on NUCLEO-H743ZI2.

DMA: Implement Serial transmit and receive

---

src/rng.rs

Add compile error reminding to build with the correct target

---

README.md

Bump cortex-m version in README

---

src/rtc.rs

Some small tweaks to the RTC initialization that I found while debugging, and added a note to LSE CSS configuration about an errata.

RTC Improvements

---

src/pwr.rs

Add explict error message when both rm0433 and smps are selected

---

examples/rtic_low_power.rs
examples/spi-dma-rtic.rs

https://rust-lang.github.io/rust-clippy/master/index.html#inconsistent_struct_constructor

Satisfy clippy by initialising LateResources in (alphabetical?) order

---

src/serial.rs

Fix inverted UART parity configuration

---

src/i2c.rs

Previously this code was calculating scldel/sdadel values > 15 which were correct, but could not be successfully used by the hardware.
Update divider calculations to generally pick a larger prescaler value, resulting in a slower scaled clock. This means that scldel/sdadel values up to 15 still result in the required delays.
Fixes #238

Clamp scldel/sdadel to 4-bit and update divider calculations

---

src/serial.rs

- added proper sync mode to usarts
- added usart config options
- clockphase: clockphase,
- bitorder: bitorder,
- clockpolarity: clockpolarity,
- lastbitclockpulse: bool,

further improve usart capabilities

---

src/lib.rs
src/usb_hs.rs

I don't know if there are any downsides to automatically setting the pin speed to VeryHigh apart from power consumption.

Set ulpi pin speed to VeryHigh

---

src/ethernet/eth.rs

Patch from https://github.com/quartiq/stabilizer/pull/462
Tested that the expected registers are indeed set on a STM32H747I-DISCO
> MMC_RX_INTERRUPT_MASK:               0x0C020060  MMC Rx interrupt mask register
> MMC_TX_INTERRUPT_MASK:               0x0C20C000  MMC Tx interrupt mask register
Closes #275

Disable ethernet MAC MMC counter interrupts

---

src/rng.rs
src/spi.rs

- Adds `Copy, Clone, PartialEq, Eq`

add more traits to SPI error

---

Cargo.toml
examples/usb_passthrough.rs
examples/usb_phy_serial_interrupt.rs
examples/usb_rtic.rs
examples/usb_serial.rs
src/usb_hs.rs

USB example improvements

---

src/pwm.rs

* TIM15 CH1 option for rm0468
* TIM15 BRK option for rm0455 rm0468

Missing TIM15 pins

---

CHANGELOG.md
examples/tick_lptimer.rs
src/timer.rs

Proposed implementation for issue #148

Implement tick_timer() for LPTIM'ers

---

.gitattributes
CHANGELOG.md
src/serial.rs

serial: support reconfiguring ports, Tx/Rx pin swap, and join() for Tx/Rx

---

examples/voltage_scaling.rs
src/pwr.rs

* Add support for configuring VOS2 and VOS3
* Add example
* Improve documentation for VOS0 (closes #326)

Support VOS2 and VOS3

---

Cargo.toml
src/flash.rs

@richardeoin Please see adjusted feature flags. Thanks

Flash: Adjust feature flags to exclude stm32h750

---

CHANGELOG.md
examples/can-echo.rs
examples/exti_interrupt.rs
examples/fmc.rs
examples/fractional-pll.rs
examples/mco.rs
examples/octospi_hyperram.rs
examples/qspi_flash_memory.rs
examples/rtic.rs
examples/sdmmc.rs
examples/spi-dma-rtic.rs
src/ethernet/eth.rs
src/ethernet/mod.rs
src/gpio.rs
src/gpio/convert.rs
src/gpio/dynamic.rs
src/gpio/erased.rs
src/gpio/exti.rs
src/gpio/hal_02.rs
src/gpio/partially_erased.rs
src/usb_hs.rs

Functional part of #346 (without IntoAF restriction)

gpio rework

---

src/serial.rs

[add] Add serial Rx and Tx fifo capacity and Fifo interrupt event

---

src/delay.rs
src/pwm.rs
src/rcc/mod.rs
src/rcc/rec.rs
src/sai/pdm.rs
src/sdmmc.rs
src/spi.rs
src/timer.rs
src/xspi/mod.rs
src/xspi/octospi.rs

Now using fugit https://github.com/stm32-rs/stm32h7xx-hal/pull/321

Fix docstrings - fugit

---

examples/ethernet-nucleo-h743zi2.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/ethernet-stm32h747i-disco.rs

Document the RMII TXD1 pin in ethernet examples

---

src/adc.rs

* remove redundant CR register re-reads when checking multiple status bits
* rafactor common code in set_chan_smp()

adc: simplify cr reads and sample time code

---

examples/adc_dma.rs
src/adc.rs
src/dma/dma.rs
src/dma/macros.rs

Add example of ADC and DMA together

Add DMA TargetAddress implementations for ADC1/2/3

---

examples/usb_passthrough.rs
examples/usb_rtic.rs
examples/usb_serial.rs

Document USB peripheral allocation in USB examples

---

.github/workflows/clippy.yml

- avoids [errors popping up in PRs all of a sudden](https://github.com/stm32-rs/stm32h7xx-hal/pull/409)

pin clippy

---

Cargo.toml
examples/ethernet-nucleo-h743zi2.rs
examples/ethernet-rtic-stm32h735g-dk.rs
examples/ethernet-rtic-stm32h747i-disco.rs
examples/ethernet-stm32h747i-disco.rs

smoltcp was updated to 0.9.0 in #422

Update smoltcp dependency to 0.10.0

---

.github/workflows/clippy.yml
examples/blinky-stm32h747i-disco.rs
examples/can-echo.rs
examples/can-fd.rs
examples/display-dsi-command-teartest-stm32h747i-disco.rs
examples/display-dsi-video-stm32h747i-disco.rs
examples/display-dsi-video-teartest-stm32h747i-disco.rs
examples/ethernet-nucleo-h743zi2.rs
examples/utilities_display/display_primitives.rs
examples/utilities_display/write.rs
src/dsi.rs
src/xspi/octospi.rs
src/xspi/qspi.rs

Use a wider set of build options for clippy

Increase cargo clippy coverage in CI
